version: '3.8'

services:
  elastic:
    build: 
      context: .
      dockerfile: elastic/Dockerfile 
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - ./elastic/data01:/usr/share/elasticsearch/data
